DROP DATABASE IF EXISTS pokerdb;
CREATE DATABASE pokerdb;

CREATE TABLE pokerdb.poker_types (
	ID TINYINT UNSIGNED AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UQ_POKER_TYPES_NAME UNIQUE (NAME)
);

CREATE TABLE pokerdb.users (
	ID INTEGER UNSIGNED AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	BALANCE DECIMAL(65,18) NOT NULL,
	REG_DATE BIGINT,
	PASSWORD VARCHAR(64) NOT NULL,
	ADMIN BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (ID),
	CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);
	
CREATE TABLE pokerdb.poker_tables (
    ID INTEGER UNSIGNED AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    POKER_TYPE_ID TINYINT UNSIGNED,
    MAX_TIME TINYINT UNSIGNED NOT NULL,
    MAX_PLAYERS TINYINT UNSIGNED NOT NULL,
    BIG_BLIND DECIMAL(65,18) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_POKER_TABLE_NAME UNIQUE (NAME),
    FOREIGN KEY (POKER_TYPE_ID) REFERENCES POKERDB.POKER_TYPES(ID) ON DELETE CASCADE
);

DELIMITER /

CREATE TRIGGER pokerdb.TR_BEFORE_CREATE_TABLE BEFORE INSERT ON pokerdb.poker_tables
	FOR EACH ROW
	BEGIN
		IF (CHAR_LENGTH(NEW.name) > 30) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_NAME_LENGHT';
		end IF;
		IF (!(5 <= NEW.max_time && NEW.max_time <= 40)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_MAX_TIME';
		end IF;
	
		IF (!(2 <= NEW.max_players && NEW.max_players <= 5)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_MAX_PLAYERS';
		end IF;
	END;
/

CREATE TRIGGER pokerdb.TR_BEFORE_UPDATE_TABLE BEFORE UPDATE ON pokerdb.poker_tables
	FOR EACH ROW
	BEGIN
		IF (CHAR_LENGTH(NEW.name) > 30) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_NAME_LENGHT';
		end IF;
		IF (!(5 <= NEW.max_time && NEW.max_time <= 40)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_MAX_TIME';
		end IF;
	
		IF (!(2 <= NEW.max_players && NEW.max_players <= 5)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_POKER_TABLES_MAX_PLAYERS';
		end IF;
	END;
/

CREATE TRIGGER pokerdb.TR_BEFORE_CREATE_USER BEFORE INSERT ON pokerdb.users
	FOR EACH ROW
	BEGIN
		SET @c = CHAR_LENGTH(NEW.username);
		IF (!(3 <= @c && @c <= 20)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_USERS_USERNAME_LENGHT';
		END IF;
		
		IF (CHAR_LENGTH(NEW.password) > 64) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'CONSTRAINT_USERS_PASSWORD_LENGHT';
		END IF;
	
		SET NEW.reg_date = UNIX_TIMESTAMP();
	END;
/

DELIMITER ;

INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'ADMIN','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',TRUE);
INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'ADMIN2','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',TRUE);
INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'test','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',FALSE);
INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'test2','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',FALSE);
INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'test3','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',FALSE);
INSERT INTO POKERDB.USERS (BALANCE, USERNAME, PASSWORD, ADMIN) VALUES(10000.00,'test4','$2a$10$PVuC8V/XNVdaIcSQxQSBQ.x5DeVSOrql11mbFRUG1wZq2dlplFosq',FALSE);
	
INSERT INTO POKERDB.POKER_TYPES (NAME) VALUES('HOLDEM');
INSERT INTO POKERDB.POKER_TYPES (NAME) VALUES('CLASSIC');

INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('szerver1',1,5,5,100);
INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('#PL_125Q',2,39,5,200);
INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('Holdem fun',1,15,5,100);
INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('Classic fun',2,5,5,20);
INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('?^xW!',2,23,3,1);
INSERT INTO POKERDB.POKER_TABLES (NAME, POKER_TYPE_ID, MAX_TIME, MAX_PLAYERS, BIG_BLIND) VALUES('ûáûúüüéáûúõöüóÍ',1,33,2,10);