DROP DATABASE IF EXISTS pokerdb;
CREATE DATABASE pokerdb;

CREATE TABLE pokerdb.poker_types (
	ID TINYINT UNSIGNED AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UQ_POKER_TYPES_NAME UNIQUE (NAME)
);

CREATE TABLE pokerdb.users (
	ID INTEGER UNSIGNED AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	BALANCE DECIMAL(65,18) NOT NULL,
	REG_DATE BIGINT,
	PASSWORD VARCHAR(64) NOT NULL,
	ADMIN BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (ID),
	CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);
	
CREATE TABLE pokerdb.poker_tables (
    ID INTEGER UNSIGNED AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    POKER_TYPE_ID TINYINT UNSIGNED,
    MAX_TIME TINYINT UNSIGNED NOT NULL,
    MAX_PLAYERS TINYINT UNSIGNED NOT NULL,
    BIG_BLIND DECIMAL(65,18) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_POKER_TABLE_NAME UNIQUE (NAME),
    FOREIGN KEY (POKER_TYPE_ID) REFERENCES POKERDB.POKER_TYPES(ID) ON DELETE CASCADE
);